/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppClipboardHistory {
    }
    interface AppHome {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppClipboardHistoryElement extends Components.AppClipboardHistory, HTMLStencilElement {
    }
    var HTMLAppClipboardHistoryElement: {
        prototype: HTMLAppClipboardHistoryElement;
        new (): HTMLAppClipboardHistoryElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-clipboard-history": HTMLAppClipboardHistoryElement;
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppClipboardHistory {
    }
    interface AppHome {
        "onChangeURL"?: (event: CustomEvent<any>) => void;
        "onCopyData"?: (event: CustomEvent<any>) => void;
        "onShareDialog"?: (event: CustomEvent<any>) => void;
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-clipboard-history": AppClipboardHistory;
        "app-home": AppHome;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-clipboard-history": LocalJSX.AppClipboardHistory & JSXBase.HTMLAttributes<HTMLAppClipboardHistoryElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
